apiVersion: v1
kind: Config
users:
- name: kube-proxy
  user:
    client-certificate: /opt/k8s-node/kube-proxy.crt
    client-key: /opt/k8s-node/kube-proxy.key
clusters:
- name: vm
  cluster:
    certificate-authority: /opt/keys/ca.crt
    server: https://192.168.1.30:6443
contexts:
- context:
    cluster: vm
    user: kube-proxy
  name: my-context
current-context: my-context

