apiVersion: v1
kind: Config
users:
- name: kubelet
  user:
    client-certificate: /opt/k8s-node/kubelet.crt
    client-key: /opt/k8s-node/kubelet.key
clusters:
- name: vm
  cluster:
    certificate-authority: /opt/keys/ca.crt
    server: https://192.168.1.30:6443
contexts:
- context:
    cluster: vm
    user: kubelet
  name: my-context
current-context: my-context

